---
abstract: "Fixup handler that resizes and crops images on the fly, caching the results, and doesn't require ImageMagick."
author:
  - 'Alexander Keusch <akeusch@mms.ag>'
build_requires:
  Apache2::Request: 0
  Apache::Test: 1.12
  File::Basename: 0
  Imager: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-Imager-Resize
provides:
  Apache2::Imager::Resize:
    file: lib/Apache2/Imager/Resize.pm
    version: 0.16
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
